version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: todo_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_app?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - todo_network

  frontend:
    build:
      context: ./todo-frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://backend:8080/api
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network: